### ISSUE TITLE
Передавать пул бд-соединения в функцию создания хэндла

### ISSUE THREAD

**Issue by olegromashin** [AKitavtsev/server-post#20]
Сейчас ты таскаешь пул в каждую функцию логики. Я предлагаю вынести его из функций логики и передавать в функцию создания бд-хэндла.

**Comment by AKitavtsev** [comment]
Да, что-то делать с этим надо. Самому не нравится, думал об этом, но решил дождаться соответствующего ишью. Дождался. Подумал еще раз.
Просто так не получается, бд-хэндл у меня создается перед созданием пула. Это вызвано тем, что при создания пула у меня используются функции из хэндла newConn и close, загнанные туда по причины зависимости от  PostgreSQL. Скорее неоправданно. 
План такой. Вывожу newConn и createPool в отдельный модуль каталога Services.Impl.PostgreSQL (как сделал с миграциями). В main создаю соединение и пул. А после этого дб-хэндл, передав ему пул. Ну а дальше понятно.

Только перед этим очень хочется влить ветки 12 и 15. А, то потом работы по устранению конфликтов будет много. 12-ую  ты смотрел, а по 15-ой Кирилл молчит. Может посмотришь (может комментарии найдешь:))? Но, вообще не в первой, раз молчит, значит замечаний нет.
